server:
  port: 8090
spring:
  application:
    name: CaesarCipher
  flyway:
    baselineOnMigrate: true
    baselineDescription: baseline_migration
    baselineVersion: 1.0
    defaultSchema: test
  datasource:
    url: "jdbc:postgresql://caesar-cipher.postgres.database.azure.com:5432/caesar-cipher"
    username: "b8af9b269319" #No pude cargarlos a los secret de azure
    password: "c728155f@" #No pude cargarlos a los secret de azure
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test
    #hibernate:
    #  ddl-auto: update
    #generate-ddl: false



management:
  context-path: /actuator
  security:
    enable: true
  endpoints:
    web:
      exposure:
        include: 'health'
