server:
  port: 8090
spring:
  application:
    name: Caesar Cipher
  flyway:
    baselineOnMigrate: true
    baselineDescription: baseline_migration
    baselineVersion: 1.0
    defaultSchema: test
  datasource:
    url: "jdbc:postgresql://localhost:5433/test"
    username: "user_test"
    password: "12345"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test
    #hibernate:
    #  ddl-auto: update
    #generate-ddl: false



management:
  context-path: /actuator
  security:
    enable: true
  endpoints:
    web:
      exposure:
        include: 'health'