server:
  port: 8080
spring:
  application:
    name: CaesarCipher
  flyway:
    baselineOnMigrate: true
    baselineDescription: baseline_migration
    baselineVersion: 1.0
    defaultSchema: test
  datasource:
    url: ${URL_DATA_BASE}
    username: ${USER_DATA_BASE}
    password: $(PASS_DATA_BASE)
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test
    #hibernate:
    #  ddl-auto: update
    #generate-ddl: false



management:
  context-path: /actuator
  security:
    enable: true
  endpoints:
    web:
      exposure:
        include: 'health'